### ISSUE TITLE
Tradução do aplicativos de download

### ISSUE THREAD

**Issue by ThiagoTutorsBR** [EduardoRGCM/MIUI-XML-11-BRAZILIAN#21]
Bom seria mais interessante o aplicativo de download se chamar "Downloads" ao invés de "Transferências"

**Comment by RicardoGuariento** [comment]
Cara, até hoje eu não sei porque diabos não sai traduzido. Dentro do app já tem a linha de tradução: "<string name="app_label">Downloads</string>". Só que não é reconhecida, não sei o porquê.
